name: "Deploy Project"
on: ["push", "workflow_dispatch"]
jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        uses: npm install
      - name: Lint
        run: npm inst

  test:
    needs: lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        uses: npm install
      - name: test
        run: npm run test

  deploy:
    needs: test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        uses: npm install
      - name: build
        run: npm run build 
      - name: Deploy
        run: |
          echo "Deploying"
          echo "Deployed"
      